name: Build and Test Pipeline
on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - name: Gcloud docker configure asia gcr
        run: 'gcloud auth configure-docker asia.gcr.io -q'
      - name: Build docker image
        run: 'docker build -t asia.gcr.io/fabled-citadel-342513/learn-go-echo .'
      - name: Push docker image
        run: 'docker push asia.gcr.io/fabled-citadel-342513/learn-go-echo'
      - name: Terraform Init
        run: 'terraform init'
      - name: Terraform Plan
        run: 'terraform plan'
      - name: Terraform Apply
        run: 'terraform apply -auto-approve -replace=google_cloud_run_service.my_web_app'
